v 1.0
IvanMoskalenko/Programming-Course pull request #10
Opened 2021-04-15 15:50 UTC by IvanMoskalenko

2021-04-16 07:34 UTC, gsvgit requested changes

2021-04-16 07:34 UTC, gsvgit commented on src/Generator/Generator.fs
> +    System.IO.File.AppendAllText (path, text)
А зачем Append?

2021-04-16 07:34 UTC, gsvgit commented on src/Generator/Generator.fs
> +                let y = (x.Next(100) |> float) / 100.0
Там же есть взятие дабла "из коробки"

2021-04-16 07:34 UTC, gsvgit commented on src/Generator/Generator.fs
> +                if bType = "int" then
Гы-гы. Говорили-говорили про типы, про то, что строки -- не очень хорошо. Но нет.

2021-04-16 07:34 UTC, gsvgit commented on src/Generator/Generator.fs
> +let first (x, _, _, _, _, _) = x
Что? Зачем Вам картежи таких размеров? Зделайте тогда уже нормальную структуру с именованными полями.

2021-04-16 07:34 UTC, gsvgit commented on src/Generator/Main.fs
> +    | Generator of rows: int * cols: int * amount: int * sparsity: float * path: string * bType: string
Зачееем....

2021-04-16 08:04 UTC, IvanMoskalenko commented on src/Generator/Generator.fs
> +    System.IO.File.AppendAllText (path, text)
А чем плох Append?

2021-04-16 08:12 UTC, gsvgit commented on src/Generator/Generator.fs
> +    System.IO.File.AppendAllText (path, text)
В данном конкретном случае просто тем, что я не понимаю, зачем он здесь.

2021-04-16 08:14 UTC, IvanMoskalenko commented on src/Generator/Generator.fs
> +    System.IO.File.AppendAllText (path, text)
> В данном конкретном случае просто тем, что я не понимаю, зачем он здесь.

![image](https://user-images.githubusercontent.com/71129586/114993834-dc226980-9ea4-11eb-9baf-edc847345808.png)
Это разве не то, что здесь нужно?)

2021-04-16 08:17 UTC, gsvgit commented
Хоршо. Спрошу проще. Зачем Вам что-то дописывать в конец файла?
Regards,
Semyon Grigorev.


пт, 16 апр. 2021 г. в 11:14, Иван Москаленко ***@***.***>:

> *@IvanMoskalenko* commented on this pull request.
> ------------------------------
>
> In src/Generator/Generator.fs
> <https://github.com/IvanMoskalenko/Programming-Course/pull/10#discussion_r614648850>
> :
>
> > @@ -0,0 +1,41 @@
>
> +module Generator
>
> +open System
>
> +
>
> +let printMatrix (x: string [,]) path =
>
> +    let y = x.[*, 1]
>
> +    let z = x.[1, *]
>
> +    let mutable text = ""
>
> +    for i = 0 to y.Length - 1 do
>
> +        for j = 0 to z.Length - 1 do
>
> +            text <- text + x.[i, j] + " "
>
> +        text <- text + "\n"
>
> +    System.IO.File.AppendAllText (path, text)
>
>
> В данном конкретном случае просто тем, что я не понимаю, зачем он здесь.
>
> [image: image]
> <https://user-images.githubusercontent.com/71129586/114993834-dc226980-9ea4-11eb-9baf-edc847345808.png>
> Это разве не то, что здесь нужно?)
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/IvanMoskalenko/Programming-Course/pull/10#discussion_r614648850>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAA2CQD7SXQODEC3CFX3NP3TI7WW3ANCNFSM427YVMJQ>
> .
>

2021-04-20 11:23 UTC, gsvgit requested changes

2021-04-20 11:23 UTC, gsvgit commented on src/Generator/Generator.fs
> +                    then output.[j, k] <- string (rand.NextDouble() * float Int32.MaxValue)
Воу. А зачем так?

2021-04-20 11:23 UTC, gsvgit commented on src/Generator/Main.fs
> +            match argv.[5] with
Ну, про это мы сегодня говорили.

2021-04-22 08:13 UTC, gsvgit commented on src/Generator/Main.fs
> +    | Type of bType: string
А сюда вместо строки нельзя enum подсунуть?

2021-04-22 08:15 UTC, gsvgit commented on src/Generator/Generator.fs
> +        printMatrix output (x.path + "/Matrix" + string i + ".txt")
А вот так пути лучше не конкатенировать. Лучше через System.IO.Path. Иначе могут всякие платформозависимые бяки полезть, например, со слешами.

2021-04-22 08:15 UTC, gsvgit commented on src/Generator/Main.fs
> +            | Path _ -> "Specify the working directory"
Target?

2021-04-22 22:07 UTC, closed without merging