QuadTree Parallel Multiply
IvanMoskalenko/Programming-Course pull request #11
Opened 2021-04-15 21:05 UTC by IvanMoskalenko

2021-04-16 07:37 UTC, gsvgit requested changes

2021-04-16 07:37 UTC, gsvgit commented on src/QTPM/QTPM.fs
> +module QTPM
Мне казалось, или у Вас уже должно быть место, где собращны операции над матрицами, представленными в виде деревьв?

2021-04-16 07:37 UTC, gsvgit commented on tests/QTPM.Tests/Tests.fs
> +let tests =
Кстати, если инетресно, expecto умеет производительность тестировать.

2021-04-16 08:02 UTC, IvanMoskalenko commented on src/QTPM/QTPM.fs
> +module QTPM
Ну, там непараллельные операции. Или всё же лучше туда запихнуть?

2021-04-16 08:12 UTC, gsvgit commented on src/QTPM/QTPM.fs
> +module QTPM
Эм... В любом случае, у Вас есть матриц и набор операций над ней. Надо как-то это более аккуратно организовать. Сейчас решение странно выглядит.

2021-04-20 11:27 UTC, gsvgit requested changes
Тесты надо слегка доработать. Как-то странно Вы не пользуетесь возможностями экспекто. Ну и не очень понятно, почему только в одном полукольце. А с множествами сможете? Они вам для автоматов нужны, например.

2021-04-20 11:27 UTC, gsvgit commented on tests/HW8.Tests/Tests.fs
> +            let dim = rand.Next(0, 32)
А почему бы Вам аргумент функции не использовать как размер матрицы?

2021-04-22 22:07 UTC, closed without merging