HW3
IvanMoskalenko/Programming-Course pull request #3
Opened 2020-09-27 17:52 UTC by IvanMoskalenko

2020-09-30 09:44 UTC, gsvgit requested changes

2020-09-30 09:44 UTC, gsvgit commented on src/ProgrammingCourse/hw3.fs
> +            -1
То есть любое число Фибоначчи с индексом меньше о равно -1 ?

2020-09-30 09:44 UTC, gsvgit commented on src/ProgrammingCourse/hw3.fs
> +    let rec fib3Helper prev current n =
Будет не лишним между функциями добавлять пустую строку.

2020-09-30 09:44 UTC, gsvgit commented on src/ProgrammingCourse/hw3.fs
> +    let rec fib3Helper prev current n =
Мы специяльно обсуждали, что вспомогательные функции лучше прятать вовнутрь.

2020-09-30 09:44 UTC, gsvgit commented on src/ProgrammingCourse/hw3.fs
> +            let a = array2D [ [ 0; 1]; [1; 1] ]
Думается, можно не дублировать эти куски кода в азных ветках if-а

2020-09-30 10:48 UTC, IvanMoskalenko commented on src/ProgrammingCourse/hw3.fs
> +            -1
Нет, у меня вывод результата ведь так настроен: 
if result = -1
            then
                printf "It's unreal to find Fibonacci number if N below zero"
            else
                printf "Результат: "
                printfn "%A" result

2020-09-30 12:18 UTC, gsvgit commented
Смотрите мои комментарии в общем чате в Телеге.

Regards,
Semyon Grigorev.


ср, 30 сент. 2020 г. в 13:49, Иван Москаленко <notifications@github.com>:

> *@IvanMoskalenko* commented on this pull request.
> ------------------------------
>
> In src/ProgrammingCourse/hw3.fs
> <https://github.com/IvanMoskalenko/Programming-Course/pull/3#discussion_r497415966>
> :
>
> > @@ -0,0 +1,84 @@
>
> +namespace ProgrammingCourse
>
> +module hw3 =
>
> +    let rec fib1 n =
>
> +        if n = 2 || n = 1
>
> +        then
>
> +            1
>
> +        elif n = 0
>
> +        then
>
> +            0
>
> +        elif n < 0
>
> +        then
>
> +            -1
>
>
> Нет, у меня вывод результата ведь так настроен:
> if result = -1
> then
> printf "It's unreal to find Fibonacci number if N below zero"
> else
> printf "Результат: "
> printfn "%A" result
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/IvanMoskalenko/Programming-Course/pull/3#discussion_r497415966>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAA2CQCQGCSS6UJA5X5JSDLSIMEJ5ANCNFSM4R3V5OWQ>
> .
>

2020-10-01 05:50 UTC, gsvgit requested changes

2020-10-01 05:50 UTC, gsvgit commented on src/ProgrammingCourse/hw2.fs
>      let second_task y =
И снова. То есть пробелы вокруг бинарных операций, то нету.

2020-10-01 05:50 UTC, gsvgit commented on src/ProgrammingCourse/hw2.fs
>                  j <- j+1
И тут тоже пробелы.

2020-10-01 05:50 UTC, gsvgit commented on src/ProgrammingCourse/hw2.fs
>                  j <- j+1
И я просил не мешать все домашки в одну кучу.

2020-10-01 05:50 UTC, gsvgit commented on src/ProgrammingCourse/hw3.fs
> +        then
Вообще говоря, если Вы так определяете нулевое число, то второе отдельно определять не надо, оно уже вычисляется по общим правилам из нулевого и первого.

2020-10-01 05:50 UTC, gsvgit commented on src/ProgrammingCourse/hw3.fs
> +        let mutable x = 0
А зачем Вам дополнительные переменные, почему бы не смотреть просто в правильные места массива?

2020-10-01 05:50 UTC, gsvgit commented on src/ProgrammingCourse/matrices.fs
> +module matrices =
Учитывая то, какие ляпы Вы делаете в задачах, Вам придется сильно постараться, чтобы убедить меня в том, что данный код Вы написали сами.

2020-10-01 05:50 UTC, gsvgit commented on tests/ProgrammingCourse.Tests/Tests.fs
> +                then
А зачем так сложно? Просто if n < 0 then -n else n

2020-10-02 06:56 UTC, gsvgit reviewed
Кроме 4 и 5, кторые требуют матриц, всё ок. С 4 и 5 будем на паре разбираться, видимо.

2020-10-02 06:56 UTC, gsvgit commented on tests/ProgrammingCourse.Tests/Tests.fs
> +                then
Ну вот такие вещи, как обсуждалось на паре, можно и в одну строку писать.

2020-10-03 18:02 UTC, gsvgit requested changes
Уф. Совсем мелочи остались.

2020-10-03 18:02 UTC, gsvgit commented on src/ProgrammingCourse/hw3.fs
> +        elif pow = 1 then matrix
А нулевую степень куда потеряли? Она как раз единичной матрице равна. Я про неё не просто так говорил.

2020-10-03 18:02 UTC, gsvgit commented on src/ProgrammingCourse/hw3.fs
> +        let arrayOfresults : int array = Array.zeroCreate (n+1)
А до этого Вы вокруг плюса пробелы добавляли.

2020-10-03 18:51 UTC, IvanMoskalenko commented on src/ProgrammingCourse/hw3.fs
> +        elif pow = 1 then matrix
Вы вроде вчера до пары говорили, что в нулевую степень нельзя матрицу возводить

2020-10-03 18:57 UTC, gsvgit commented
Там речь про размеры шла: а нельзя ли как-то хитро определить единичную
матрицу для прямоугольных матриц. Решили, что не надо нам такое.

Regards,
Semyon Grigorev.


сб, 3 окт. 2020 г. в 21:51, Иван Москаленко <notifications@github.com>:

> *@IvanMoskalenko* commented on this pull request.
> ------------------------------
>
> In src/ProgrammingCourse/hw3.fs
> <https://github.com/IvanMoskalenko/Programming-Course/pull/3#discussion_r499172556>
> :
>
> > +    let matrix_multiply (matrix1: int[,]) (matrix2: int[,]) =
>
> +        let row1 = matrix1.[0,*].Length
>
> +        let col2 = matrix2.[*,0].Length
>
> +        let result = Array2D.zeroCreate row1 col2
>
> +        if row1 = col2
>
> +        then
>
> +            for i = 0 to row1 - 1 do
>
> +                for k = 0 to col2 - 1 do
>
> +                    for r = 0 to row1 - 1 do
>
> +                            result.[i,k] <- result.[i,k] + matrix1.[i,r] * matrix2.[r,k]
>
> +            result
>
> +        else failwith "Matrices isn't matched"
>
> +
>
> +    let matrix_power (matrix: int[,]) pow =
>
> +        if pow < 1 then failwith "It's unreal to find Matrix power zero or below"
>
> +        elif pow = 1 then matrix
>
>
> Вы вроде вчера до пары говорили, что в нулевую степень нельзя матрицу
> возводить
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/IvanMoskalenko/Programming-Course/pull/3#discussion_r499172556>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAA2CQE4D3RDPQAIV3TKBPDSI5XCVANCNFSM4R3V5OWQ>
> .
>

2020-10-03 19:39 UTC, gsvgit requested changes

2020-10-03 19:39 UTC, gsvgit commented on src/ProgrammingCourse/hw3.fs
> +            let rows = matrix.[0,*].Length
Теперь, когда у Вас есть единичная матрица, весь этот код можно упростить, так как она является единицей по умножению и теперь просто с нее можно считать степень

2020-10-04 13:36 UTC, gsvgit requested changes

2020-10-04 13:36 UTC, gsvgit commented on src/ProgrammingCourse/hw3.fs
> +                let pow = n / 2
Только сейчас понял, что Вы только один раз делите степень на 2. Это не совсем то. Это всего один шаг. Вероятно, проще будет реализовать две разные функции возведения в степень.

2020-10-04 13:36 UTC, gsvgit commented on tests/ProgrammingCourse.Tests/Tests.fs
>  let tests =
Не сваливайте все тесты в одну кучу. Создате несколько наборов тестов. Хотя бы по набору на задачу. Разделите существующие на логические группы.

2020-10-13 06:26 UTC, gsvgit requested changes

2020-10-13 06:26 UTC, gsvgit commented on src/ProgrammingCourse/hw3.fs
> +            let resultMatrix = matrixPower (smartMatrixPower matrix (pow / 2)) 2
Зачем так чложно? Просто 
```
then matrixPower (smartMatrixPower matrix (pow / 2)) 2
```

2020-10-13 06:26 UTC, gsvgit commented on src/ProgrammingCourse/hw3.fs
> +            let resultMatrix = matrixMultiply (matrixPower (smartMatrixPower matrix ((pow - 1) / 2)) 2) (matrix)
То же самое, ещё скобк лишние вокруг matrix

2020-10-13 06:26 UTC, gsvgit commented on src/ProgrammingCourse/hw3.fs
> +                arrayOfresults.[i] <- arrayOfresults.[i-1] + arrayOfresults.[i-2];
А ```;``` лишняя.

2020-10-13 06:26 UTC, gsvgit commented on tests/ProgrammingCourse.Tests/Tests.fs
> +            let testPropertyHelper n =
Вообще, хэлпер можно ещё на уровень выше вынести. Пред testList.

2020-10-13 06:26 UTC, gsvgit commented on tests/ProgrammingCourse.Tests/Tests.fs
> +                if n < 0 then -n else n
А вообще, есть стандартная функция abs

2020-10-14 09:56 UTC, gsvgit approved these changes
Ок. Но ```push --force``` --- зло, которое говорит, что Вы где-то накосячили в коммитах.

2020-10-14 14:55 UTC, merged